// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP03_Douglas_Lucas.Models.SqlContext;

#nullable disable

namespace TP03_Douglas_Lucas.Migrations
{
    [DbContext(typeof(SqlContext))]
    partial class SqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TP03_Douglas_Lucas.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Categoria");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Descricao");

                    b.Property<string>("Nome")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Preco");

                    b.Property<int>("Unidade")
                        .HasColumnType("int")
                        .HasColumnName("Unidade");

                    b.HasKey("Id");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Ele tronico",
                            Descricao = "CElular preto com capa preta andoid 18 meses de uso xioami poco x5 vem no precingo pv",
                            Nome = "Celular do dougla",
                            Preco = 2000m,
                            Unidade = 1
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Ele tronico",
                            Descricao = "Celular branco com capa azul do kuquinhas nem parece branco vem no pv compra rapido",
                            Nome = "Celular do luquinha",
                            Preco = 5000m,
                            Unidade = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
